name: Java CI Pipeline

on:
  push:
    branches: [ "master" ,"develop-the-backend-for-an-e-commerce-system-28151"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test
        run: ./mvnw clean install